import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import localFont from "next/font/local"; 
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import Breadcrumbs from "@/components/Breadcrumbs/Breadcrumbs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta',
  style: ['normal'],
  weight: ['600'] 
});

const skModernist = localFont({
  src: '../public/fonts/sk-modernist-regular-webfont.woff2', 
  weight: '400',
  style: 'normal',
  variable: '--font-sk-modernist',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${plusJakartaSans.variable} ${skModernist.variable} antialiased`}
    >
      <body className="">
        <Navbar />
        <Breadcrumbs />
        
        <main className="flex-1 w-full">
          {children}
        </main>
        
        <Footer />
      </body>
    </html>
  );
}

