import type { Metadata } from "next";
import {  Plus_Jakarta_Sans } from "next/font/google";
import localFont from "next/font/local"; 
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import Breadcrumbs from "@/components/Breadcrumbs/Breadcrumbs";



const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta',

});

const skModernist = localFont({
  src: '../public/fonts/sk-modernist-regular-webfont.woff2', 
  variable: '--font-sk-modernist',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={` ${plusJakartaSans.variable} ${skModernist.variable} antialiased`}
    >
      <body className="">
        <Navbar />
        <Breadcrumbs />
        
        <main className="flex-1 w-full">
          {children}
        </main>
        
        <Footer />
      </body>
    </html>
  );
}

